import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // ── LEARN ────────────────────────────────────────────────────────
  learnSidebar: [
    {
      type: "category",
      label: "Learn",
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Concepts",
          collapsed: false,
          items: [
            "learn/concepts/index",
            "learn/concepts/step-0-phase",
            "learn/concepts/hulyapulse",
            "learn/concepts/zeqond",
            "learn/concepts/r-of-t",
            "learn/concepts/ko42",
            "learn/concepts/operators",
            "learn/concepts/master-equation",
            "learn/concepts/seven-step-protocol",
            "learn/concepts/zeqproof",
            "learn/concepts/degradation-model",
            "learn/concepts/precision-bound",
            "learn/concepts/cko",
            "learn/concepts/zid",
            "learn/concepts/zeqstate",
            "learn/concepts/plnb",
          ],
        },
      ],
    },
  ],

  // ── BUILD ────────────────────────────────────────────────────────
  buildSidebar: [
    {
      type: "category",
      label: "Quickstart",
      collapsed: false,
      items: [
        "build/quickstart/introduction",
        "build/quickstart/quickstart",
        "build/quickstart/authentication",
        "build/quickstart/first-computation",
        "build/quickstart/understanding-responses",
      ],
    },
    {
      type: "category",
      label: "Language Clients",
      collapsed: false,
      items: [
        "build/clients/overview",
        "build/clients/javascript",
        "build/clients/python",
        "build/clients/go",
        "build/clients/rust",
        "build/clients/curl",
      ],
    },
    {
      type: "category",
      label: "Domain Recipes",
      collapsed: true,
      items: [
        "build/recipes/medical-imaging",
        "build/recipes/game-physics",
        "build/recipes/emergency-systems",
        "build/recipes/hardware-design",
        "build/recipes/robotics",
        "build/recipes/weather-agriculture",
        "build/recipes/water-infrastructure",
        "build/recipes/forensics-security",
      ],
    },
  ],

  // ── REFERENCE ────────────────────────────────────────────────────
  referenceSidebar: [
    {
      type: "category",
      label: "Protocols (234)",
      collapsed: false,
      link: { type: "doc", id: "reference/protocols/index" },
      items: [
        {
          type: "autogenerated",
          dirName: "reference/protocols",
        },
      ],
    },
    {
      type: "category",
      label: "Operators",
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "reference/operators",
        },
      ],
    },
    {
      type: "category",
      label: "API",
      collapsed: true,
      items: [
        "reference/api/endpoints",
        {
          type: "category",
          label: "Core endpoints",
          collapsed: false,
          items: [
            "reference/api/core/compute",
            "reference/api/core/lattice",
            "reference/api/core/shift",
            "reference/api/core/verify",
            "reference/api/core/pulse",
            "reference/api/core/genesis",
            "reference/api/core/operators",
            "reference/api/core/framework",
            "reference/api/core/mesh",
            "reference/api/core/dns",
            "reference/api/core/daemon",
            "reference/api/core/hite",
            "reference/api/core/text",
            "reference/api/core/compress",
            "reference/api/core/mail",
            "reference/api/core/llm",
            "reference/api/core/mcp",
            "reference/api/core/portal",
            "reference/api/core/playground",
          ],
        },
        "reference/api/zeqstate-object",
        "reference/api/error-codes",
        "reference/api/openapi",
        "reference/api/daemon-api",
        "reference/api/mail-api",
        "reference/api/mesh-api",
      ],
    },
  ],

  // ── OPERATE ──────────────────────────────────────────────────────
  operateSidebar: [
    {
      type: "category",
      label: "Operate",
      collapsed: false,
      items: [
        "operate/overview",
        "operate/error-handling",
        "operate/rate-limits",
        "operate/webhooks",
      ],
    },
  ],
};

export default sidebars;
